### ISSUE TITLE
Istio Implementation

### ISSUE THREAD

**Issue by dshimo** [ibm-cloud-architecture/refarch-cloudnative-micro-inventory#114]
Stage 1

- [x] Virtual Service, Auth Policy, Destination Rule ( PR #113 )

- [x] Gateway

Stage 2

~- [ ] Additional Istio features TBD~

**Comment by dshimo** [comment]
- [x] Document Enabling RabbitMQ when deploying Inventory Standalone

- [x] ~Document starting the Helm Chart with Istio~ Set `istio.enabled` flag to true when deploying

**Comment by phemankita** [comment]
@dshimo - Are you working on this issue ?

**Comment by yeekangc** [comment]
@kevinwlau @jjvilleg, is this still relevant?

**Comment by evie-lau** [comment]
These are completed now, and I've updated the checkboxes in the original comments.
