### ISSUE TITLE
Emphasize that the IP address of the database should be the one returned in "docker inspect mysql"

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-cloudnative-micro-inventory#9]
I'm running locally in my Docker machine.

To deploy this application, the instructions say,

Start the application in docker container. Replace {docker-host} with IP address of the docker-machine, {dbuser} with database user name and {password} with database user password.

I tried different values for the docker-host (127.0.0.1, localhost). After @gangchen03's help, I could configure properly, but using the IP returned by 

docker inspect mysql

Please emphasize the need for the right IP in this step.

Thanks

**Comment by gangchen03** [comment]
Updated the git instruction on getting the right MySQL IP address when using different Docker versions. Change is in branch https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/r1defect
